import sys
import time
import os
from termcolor import colored

class Utilities:
    '''This class contains utilities functions'''
    def __init__(self) -> None:
        pass
    
    def ClearConsole(self):
        '''Clears the console'''
        if os.name == 'nt':
            os.system('cls')
        else:
            os.system('clear')

    def SleepConsole(self, timer):
        '''Pause the application for a given amount of time'''
        time.sleep(timer)
    
    def PrintMenuTitle(self, title):
        '''Displays the menu title'''
        print(f"-----    {title}    -----\n")

    def SuccessMessage(self, message):
        '''Displays a success message'''
        message = colored(message, "green", attrs=['bold'])
        return message
    def ConsoleMessage(self, message):
        '''Displays a message generated by the console'''
        message = colored(message, "yellow", attrs=['bold'])
        return message
    def ErrorMessage(self, message):
        '''Displays an error message'''
        message = colored(message, "red", attrs=['bold'])
        return message
    def ReturnMessage(self, message):
        '''Displays a return to home message'''
        message = colored(message, "blue", attrs=['bold'])
        return message

    def QuitApplication(self):
        '''Handles the closing of the application'''
        print(self.ConsoleMessage("Closing application..."))
        self.SleepConsole(1.1)
        self.ClearConsole()
        sys.exit()
